#!/usr/bin/env bash
# Renders the Homebrew formula for a release from its SHA256SUMS file.
#
#   scripts/homebrew-formula.sh <version> <SHA256SUMS> > Formula/gws-rust.rb
#
# The formula installs the prebuilt `gwsr` binary: native builds on macOS and static musl builds
# on Linux. Every referenced archive must be listed in SHA256SUMS or the script fails.
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 <version> <SHA256SUMS>" >&2
  exit 2
fi
version="$1"
sums_file="$2"

if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "error: Homebrew formulae are only published for stable versions, got: ${version}" >&2
  exit 1
fi
if [[ ! -r "$sums_file" ]]; then
  echo "error: cannot read ${sums_file}" >&2
  exit 1
fi

readonly repo_url="https://github.com/astelmach20/gws-rust"

sha_for() {
  local name="gws-rust-${version}-$1.tar.gz" sha
  sha="$(awk -v f="$name" '$2 == f || $2 == "*" f { print $1 }' "$sums_file")"
  if [[ ! "$sha" =~ ^[0-9a-f]{64}$ ]]; then
    echo "error: no valid SHA-256 for ${name} in ${sums_file}" >&2
    return 1
  fi
  printf '%s' "$sha"
}

url_for() {
  printf '%s/releases/download/v%s/gws-rust-%s-%s.tar.gz' "$repo_url" "$version" "$version" "$1"
}

darwin_arm="$(sha_for aarch64-apple-darwin)"
darwin_x64="$(sha_for x86_64-apple-darwin)"
linux_arm="$(sha_for aarch64-unknown-linux-musl)"
linux_x64="$(sha_for x86_64-unknown-linux-musl)"

cat <<FORMULA
# typed: strict
# frozen_string_literal: true

# Generated by scripts/homebrew-formula.sh in ${repo_url}; do not edit by hand.
class GwsRust < Formula
  desc "Google Workspace CLI with a dynamic command surface from the Discovery Service"
  homepage "${repo_url}"
  version "${version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$(url_for aarch64-apple-darwin)"
      sha256 "${darwin_arm}"
    end
    on_intel do
      url "$(url_for x86_64-apple-darwin)"
      sha256 "${darwin_x64}"
    end
  end

  on_linux do
    on_arm do
      url "$(url_for aarch64-unknown-linux-musl)"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "$(url_for x86_64-unknown-linux-musl)"
      sha256 "${linux_x64}"
    end
  end

  def install
    bin.install "gwsr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gwsr --version")
  end
end
FORMULA
